### ISSUE TITLE
Google Mobile Ads Unity Plugin v6.0.0

### ISSUE THREAD

**Issue by MeAtPros** [googleads/googleads-mobile-unity#1613]
Exception: Failed running /Applications/Unity/Hub/Editor/2021.1.4f1/Unity.app/Contents/il2cpp/build/deploy/netcoreapp3.1/UnityLinker @"/Unity/Temp/StagingArea/assets/bin/Data/Managed/response.rsp"

stdout:
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'
 ---> System.InvalidOperationException: No action for the assembly GoogleMobileAds.Unity, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null defined
   at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Annotations.cs:line 112
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 574
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 1447
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.<>c__DisplayClass20_4.<HandleCall>b__7() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 810
   at Mono.Linker.Dataflow.ReflectionPatternContext.RecordRecognizedPattern(IMemberDefinition accessedItem, Action mark) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionPatternContext.cs:line 79
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams, ValueNode& methodReturnValue) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 811
   at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/MethodBodyScanner.cs:line 859
   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/MethodBodyScanner.cs:line 530
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs:line 69
   at Unity.Linker.Steps.UnityMarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 356
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 2810
   at Unity.Linker.Steps.UnityMarkStep.MarkMethodBody(MethodBody body) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 362
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 2432
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 227
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 391
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 393
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue() in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 377
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 188
   at Unity.Linker.Steps.UnityMarkStep.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker.Steps/UnityMarkStep.cs:line 260
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityPipeline.cs:line 23
   at Mono.Linker.Pipeline.Process(LinkContext context) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Pipeline.cs:line 129
   at Unity.Linker.UnityDriver.UnityRun(ILogger customLogger) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 106
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(ILogger customLogger) in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 72
   at Unity.Linker.UnityDriver.RunDriver() in /Users/bokken/build/output/unity/il2cpp/UnityLinker/Linker/UnityDriver.cs:line 54
stderr:

**Comment by NilokiloxD** [comment]
Can confirm this, any fix planned? 
Also Unity is complaining that the assembly can not be the same name as the dll.

**Comment by adnanse-hadali** [comment]
Got the same error using Unity version 2021.1.6
Solution will be a great help.
Thanks

**Comment by rajabilal555** [comment]
Got the same error.
Unity version: **2021.1.5f1**
Hope this gets fixed soon.

Screenshot of Player Settings:
![image](https://user-images.githubusercontent.com/15360941/118786981-ca6d2100-b8ab-11eb-84cc-0cae5b200d76.png)

**Comment by JillSong** [comment]
Hey everybody, I'm tackling the issue with our team. I'm able to reproduce the issue only on 2021.1 version (2020.2 works fine) Does anyone have issue on Unity 2020?

**Comment by JillSong** [comment]
For a quick fix, you can import the source code Asset into your project. https://github.com/googleads/googleads-mobile-unity/tree/master/source/plugin/Assets This will get rid of the exception.

**Comment by shirokurohitsuji** [comment]
> Hey everybody, I'm tackling the issue with our team. I'm able to reproduce the issue only on 2021.1 version (2020.2 works fine) Does anyone have issue on Unity 2020?

I don't have this compile error in 2020.3.8f1.
In 2020, there just seems to be a build error (#1616)

**Comment by nomibuilder** [comment]
Got the same error using Unity version 2021.1.6
Please fix this.

**Comment by horoeil** [comment]
I have the same problem. Q口Q

**Comment by p-inemu** [comment]
2021.1.10f. Same problem

**Comment by joshpeterson** [comment]
> Hey everybody, I'm tackling the issue with our team. I'm able to reproduce the issue only on 2021.1 version (2020.2 works fine) Does anyone have issue on Unity 2020?

Unity developer here - @JillSong It sounds like this is a change in behavior in Unity, so we would like to understand and correct this, even if you have a work around on your end. Can you drop us a bug report with a Unity project that causes this issue?

https://unity3d.com/unity/qa/bug-reporting

**Comment by JillSong** [comment]
Closing the issue. The fix will be in the next release.

**Comment by Makizume** [comment]
> Closing the issue. The fix will be in the next release.

Hi I am very new here for solving this problem.
I was wondering if you can tell me how to fix this issue for me? 

I was trying to follow exactly your instruction.
however, it is just my luck of my knowledge, I could not figure out how where I can change and how to change it.
especially (source/plugin/Assets/GoogleMobileAds/Api/Core/AdRequest.cs).

in Unity, I could only find these .cs files...
with your instruction, I was supposed to change 6.0.0 => 6.0.1, but I could not find anywhere in my project.

could you please kindly advise?
My Unity version is 2021.2.0a21.2949
Thank you so much.
Shota

![Screen Shot 2021-06-19 at 18 07 06](https://user-images.githubusercontent.com/86147909/122637367-318b2900-d129-11eb-963e-bb6ec2a75208.png)

**Comment by Hetagkaty** [comment]
> Closing the issue. The fix will be in the next release.

Please tell me when the update will be released?

**Comment by Zamaroht** [comment]
Do we have an ETA on the fixed release?

**Comment by Zamaroht** [comment]
I still have the same problem with builds after updating to 6.0.1 SDK.

```
Exception: Failed running /Applications/Unity/2021.1.10f1/Unity.app/Contents/il2cpp/build/deploy/netcoreapp3.1/UnityLinker @"/Users/zamaroht/Documents/splabs/blackboard/Temp/StagingArea/Data/Managed/response.rsp"

stdout:
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'
 ---> System.InvalidOperationException: No action for the assembly GoogleMobileAds.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null defined
   at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Annotations.cs:line 112
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 574
```

I tried building with Unity 2021.1.4f1 and 2021.1.10f1, both give me the same problem. I'm on Mac.

**Comment by YianChen75** [comment]
i have problem updating to 6.0.1 SDK.

Unity 2020.3.7f1

Assets/GoogleMobileAdsMediationTestSuite/Api/MediationTestSuite.cs(85,23): error CS0433: The type 'AdRequest' exists in both 'GoogleMobileAds.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'GoogleMobileAds, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by davit87yeghoyan** [comment]
I still have the same problem with builds after updating to 6.0.1 SDK.
macBook M1

**Comment by Zamaroht** [comment]
> I still have the same problem with builds after updating to 6.0.1 SDK.
> 
> ```
> Exception: Failed running /Applications/Unity/2021.1.10f1/Unity.app/Contents/il2cpp/build/deploy/netcoreapp3.1/UnityLinker @"/Users/zamaroht/Documents/splabs/blackboard/Temp/StagingArea/Data/Managed/response.rsp"
> 
> stdout:
> Fatal error in Unity CIL Linker
> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'
>  ---> System.InvalidOperationException: No action for the assembly GoogleMobileAds.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null defined
>    at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Annotations.cs:line 112
>    at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 574
> ```
> 
> I tried building with Unity 2021.1.4f1 and 2021.1.10f1, both give me the same problem. I'm on Mac.

After a few days of trial and error, I found what was wrong and don't have this linker error any more.

My use case was as follows: I was trying to create a package with this plugin inside, which is then uploaded to a package registry. Then, I was importing the package inside my project from the package registry and trying to compile. Compiling failed with the linker error in the quoted message.

To fix it, I copied the link.xml and link.xml.meta files from the package directly into the project's Assets directory. After doing this the error is gone. Looks like Unity is not reading this link.xml file if it is inside a package from a package registry.

**Comment by Danil123456789** [comment]
> > I still have the same problem with builds after updating to 6.0.1 SDK.
> > ```
> > Exception: Failed running /Applications/Unity/2021.1.10f1/Unity.app/Contents/il2cpp/build/deploy/netcoreapp3.1/UnityLinker @"/Users/zamaroht/Documents/splabs/blackboard/Temp/StagingArea/Data/Managed/response.rsp"
> > 
> > stdout:
> > Fatal error in Unity CIL Linker
> > Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'
> >  ---> System.InvalidOperationException: No action for the assembly GoogleMobileAds.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null defined
> >    at Mono.Linker.AnnotationStore.GetAction(AssemblyDefinition assembly) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker/Annotations.cs:line 112
> >    at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember) in /Users/bokken/build/output/unity/il2cpp/repos/monolinker/src/linker/Linker.Steps/MarkStep.cs:line 574
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried building with Unity 2021.1.4f1 and 2021.1.10f1, both give me the same problem. I'm on Mac.
> 
> After a few days of trial and error, I found what was wrong and don't have this linker error any more.
> 
> My use case was as follows: I was trying to create a package with this plugin inside, which is then uploaded to a package registry. Then, I was importing the package inside my project from the package registry and trying to compile. Compiling failed with the linker error in the quoted message.
> 
> To fix it, I copied the link.xml and link.xml.meta files from the package directly into the project's Assets directory. After doing this the error is gone. Looks like Unity is not reading this link.xml file if it is inside a package from a package registry.

Как выглядит ваш link.xml и из какой папки вы переместили его? Просто столкнулся с такой-же проблемой и не могу решить.

**Comment by Arman11** [comment]
Hi there! Mac OS, Unity 2022.1.15f1, GoogleMobileAds 7.2.0, IL2CPP 
-> 
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: GoogleMobileAds.Api.MobileAds.GetClientFactory(): Error processing method 'GoogleMobileAds.Api.MobileAds.GetClientFactory()' in assembly 'GoogleMobileAds.dll'

I try to copy/paste link.xml to assets root, but it's not affect. :(

**Comment by fedorenkosergiy** [comment]
There is a workaround [here](https://issuetracker.unity3d.com/issues/android-could-not-build-an-il2cpp-project-when-using-googlemobileads-dot-dll)

**Comment by Difficulty-in-naming** [comment]
`  <assembly fullname="GoogleMobileAds.iOS" ignoreIfMissing="1">
    <namespace fullname="GoogleMobileAds" preserve="all" />
    <namespace fullname="GoogleMobileAds.iOS" preserve="all" />
  </assembly>
  <assembly fullname="GoogleMobileAds.Android" ignoreIfMissing="1">
    <namespace fullname="GoogleMobileAds" preserve="all" />
    <namespace fullname="GoogleMobileAds.Android" preserve="all" />
  </assembly>
`
Add the code to link.xml and it works fine

**Comment by gothicserpent** [comment]
Once I downgraded from `Unity 2022.1.19f1` to `Unity 2021.3.11f1` it worked.

I hope someone resolves this for the `Unity 2022` builds. Please keep working on this to ensure it's not there in our next versions!

**Comment by badrdouah** [comment]
the problem is still there , Unity 2022.1.20
any help to get this sorted,

**Comment by hippogamesunity** [comment]
Hi, after upgrading Unity from 2021 to 2022 this error appeared. I'm using 7.3.0 and there are no issues witn 2020/2021 LTS.

**Comment by egorovsa** [comment]
> Hi, after upgrading Unity from 2021 to 2022 this error appeared. I'm using 7.3.0 and there are no issues witn 2020/2021 LTS.

Absolutely the same!
Unity 2022.1.21f1
GoogleMobileAds  7.3.0

**Comment by hippogamesunity** [comment]
@JillSong Hi, please reopen.

**Comment by Cereal-Killa** [comment]
Same issue here, 2022.1.10f1

**Comment by nitro577** [comment]
Same problem with 2022.1.21f1, works fine with 2021.2.19f1, GoogleMobileAds v. 7.0.0

**Comment by nitro577** [comment]
Unity 2022.1.21f1, GoogleMobileAds 7.0.0
Editing `link.xml` (as a workaround) resolves the problem, but it looks like the issue is related to Unity itself. In the Inspector (Import Settings), it's not possible to exclude **GoogleMobileAds.iOS.dll** from Android build. While "All Platforms" and every platform in the "Include platforms" section are unchecked, it causes an error (on build):

`Building Library\Bee\artifacts\Android\d8kzr\libil2cpp.so failed with output:
Library/Bee/artifacts/Android/d8kzr/wkmd_ileAds.iOS.o: In function ***:
.../Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.iOS.cpp:7684: undefined reference to GADUGetAdErrorCode
.../Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.iOS.cpp:7684: undefined reference to GADUGetAdErrorCode
<etc>`

To workaround that issue (Android builds) backup and remove **GoogleMobileAds.iOS.dll**, also remove the following folders from the Library folder (/path_to_your_project/Library):

- Artifacts
- Bee
- BuildPlayerData

Also, may need to remove il2cpp cache folders. Then rebuild.

**link.xml**:
`<linker>
	<assembly fullname="GoogleMobileAds.iOS" ignoreIfMissing="1">
		<namespace fullname="GoogleMobileAds" preserve="all" />
		<namespace fullname="GoogleMobileAds.iOS" preserve="all" />
	</assembly>
	<assembly fullname="GoogleMobileAds.Android" ignoreIfMissing="1">
		<namespace fullname="GoogleMobileAds" preserve="all" />
		<namespace fullname="GoogleMobileAds.Android" preserve="all" />
	</assembly>
	<assembly fullname="GoogleMobileAds.Unity" ignoreIfMissing="1">
		<namespace fullname="GoogleMobileAds" preserve="all" />
		<namespace fullname="GoogleMobileAds.Unity" preserve="all" />
	</assembly>
</linker>
`

**Comment by brillliant** [comment]
> k like and from which folder did yo



> 

no working solitions here

**Comment by heamomo** [comment]
> Unity 2022.1.21f1, GoogleMobileAds 7.0.0 Editing `link.xml` (as a workaround) resolves the problem, but it looks like the issue is related to Unity itself. In the Inspector (Import Settings), it's not possible to exclude **GoogleMobileAds.iOS.dll** from Android build. While "All Platforms" and every platform in the "Include platforms" section are unchecked, it causes an error (on build):
> 
> `Building Library\Bee\artifacts\Android\d8kzr\libil2cpp.so failed with output: Library/Bee/artifacts/Android/d8kzr/wkmd_ileAds.iOS.o: In function ***: .../Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.iOS.cpp:7684: undefined reference to GADUGetAdErrorCode .../Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.iOS.cpp:7684: undefined reference to GADUGetAdErrorCode <etc>`
> 
> To workaround that issue (Android builds) backup and remove **GoogleMobileAds.iOS.dll**, also remove the following folders from the Library folder (/path_to_your_project/Library):
> 
> * Artifacts
> * Bee
> * BuildPlayerData
> 
> Also, may need to remove il2cpp cache folders. Then rebuild.
> 
> **link.xml**: `<linker> <assembly fullname="GoogleMobileAds.iOS" ignoreIfMissing="1"> <namespace fullname="GoogleMobileAds" preserve="all" /> <namespace fullname="GoogleMobileAds.iOS" preserve="all" /> </assembly> <assembly fullname="GoogleMobileAds.Android" ignoreIfMissing="1"> <namespace fullname="GoogleMobileAds" preserve="all" /> <namespace fullname="GoogleMobileAds.Android" preserve="all" /> </assembly> <assembly fullname="GoogleMobileAds.Unity" ignoreIfMissing="1"> <namespace fullname="GoogleMobileAds" preserve="all" /> <namespace fullname="GoogleMobileAds.Unity" preserve="all" /> </assembly> </linker> `

It works !!!!! Thx a lot <3

**Comment by ProtoCorey** [comment]
This seems to appear in 2022.2.2f1 and 2022.2.3f1, it does NOT happen in 2022.2.1f1 (retested this after failing the other 2 builds). If I build with 2022.2.1f1 and THEN with 2022.2.3f (without deleting the library folder) I get past this first error on to the

.../Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.iOS.cpp:7684: undefined reference to GADUGetAdErrorCode

the link.xml workaround does not work. currently trying to delete the IOS dll manually (though, this would mean we need a manual build and can't use our build chain)

**Comment by wentaoma** [comment]
> Unity 2022.1.21f1, GoogleMobileAds 7.0.0 Editing `link.xml` (as a workaround) resolves the problem, but it looks like the issue is related to Unity itself. In the Inspector (Import Settings), it's not possible to exclude **GoogleMobileAds.iOS.dll** from Android build. While "All Platforms" and every platform in the "Include platforms" section are unchecked, it causes an error (on build):
> 
> `Building Library\Bee\artifacts\Android\d8kzr\libil2cpp.so failed with output: Library/Bee/artifacts/Android/d8kzr/wkmd_ileAds.iOS.o: In function ***: .../Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.iOS.cpp:7684: undefined reference to GADUGetAdErrorCode .../Library/Bee/artifacts/Android/il2cppOutput/cpp/GoogleMobileAds.iOS.cpp:7684: undefined reference to GADUGetAdErrorCode <etc>`
> 
> To workaround that issue (Android builds) backup and remove **GoogleMobileAds.iOS.dll**, also remove the following folders from the Library folder (/path_to_your_project/Library):
> 
> * Artifacts
> * Bee
> * BuildPlayerData
> 
> Also, may need to remove il2cpp cache folders. Then rebuild.
> 
> **link.xml**: `<linker> <assembly fullname="GoogleMobileAds.iOS" ignoreIfMissing="1"> <namespace fullname="GoogleMobileAds" preserve="all" /> <namespace fullname="GoogleMobileAds.iOS" preserve="all" /> </assembly> <assembly fullname="GoogleMobileAds.Android" ignoreIfMissing="1"> <namespace fullname="GoogleMobileAds" preserve="all" /> <namespace fullname="GoogleMobileAds.Android" preserve="all" /> </assembly> <assembly fullname="GoogleMobileAds.Unity" ignoreIfMissing="1"> <namespace fullname="GoogleMobileAds" preserve="all" /> <namespace fullname="GoogleMobileAds.Unity" preserve="all" /> </assembly> </linker> `

Workd for me

**Comment by gmisoftwares** [comment]
Modifying the linker fixed it for me. Thanks Nitro577
