### ISSUE TITLE
Error on Unity 5.5.0f3, iOS

### ISSUE THREAD

**Issue by salgado18** [googleads/googleads-mobile-unity#317]
On importing an existing project (that worked on Unity 5.4.3), this error occur on lines 82 to 86 on iOS platform:

Assets/GoogleMobileAds/Platforms/iOS/NativeExpressAdClient.cs(82,26): error CS0176: Static member `GoogleMobileAds.iOS.NativeExpressAdClient.NativeExpressAdViewDidReceiveAdCallback(System.IntPtr)' cannot be accessed with an instance reference, qualify it with a type name instead

**Comment by rampara** [comment]
@salgado18 are you using the latest version of the plugin? This sounds like a issue that was resolved in a previous release.

**Comment by salgado18** [comment]
Just checked the current source file, and it has the fix I implemented locally, so no, I have an older version. Sorry :P
