### ISSUE TITLE
Support for Google Mobile Ads iOS SDK 8.0.0 

### ISSUE THREAD

**Issue by qbit86** [googleads/googleads-mobile-unity#1569]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2018.4.10f1
  * Google Mobile Ads Unity plugin version: **5.4.0**
  * Google Mobile Ads iOS SDK version: **8.0.0**
  * Platform: iOS
  * Mediation ad networks used, and their versions:
    - Facebook Audience Network
      - GoogleMobileAdsFacebookMediation-3.2.0
      - FBAudienceNetwork-6.2.1
      - FacebookAdapter-6.2.1.0
    - Many other

#### Steps to reproduce:

> What happened? How can we make the problem occur?

The project fails to build after updating native iOS SDK from 7.68.0 to 8.0.0:
```
/Users/buildserver/…/Libraries/Plugins/iOS/GADURewardedAd.m:12:31: error: cannot find protocol declaration for 'GADRewardedAdDelegate'; did you mean 'GADNativeAdDelegate'?
…
/Users/buildserver/…/Libraries/Plugins/iOS/GADURewardedAd.m:27:42: error: no visible @interface for 'GADRewardedAd' declares the selector 'initWithAdUnitID:'
…
```

When will update for Google Mobile Ads Unity Plugin be available?

The latest published release is 5.4.0 at the moment:
> Google Mobile Ads Unity Plugin v5.4.0
> @stowy released this on Nov 13, 2020
> — https://github.com/googleads/googleads-mobile-unity/releases/

**Comment by qbit86** [comment]
@stowy Are there any updates on this?

**Comment by qbit86** [comment]
@lsnose Do you have any ETA on this critical update?

**Comment by Personuo** [comment]
Google reminded me that new packages must use 7.65.0 or above, but gmu 5.4 only supports up to 7.68.0, I am worried that my released package will lose maintenance immediately.

**Comment by ericleich** [comment]
Unfortunately @stowy no longer works on AdMob and that's part of the reason this support has been delayed. The good news is we are well aware that the plugin is not compatible with 8.0.0 and are actively working to get this updated. Please hang in there!

Using the Unity 5.4.0 release with iOS 7.68.0 is the recommended solution in the short term. There's no requirement from Google specifically that you need to be on 8.0.0 (we have not announced any deprecations of 7.x libraries). But we also realize that there is increasing pressure from other libs who start depending on GMA 8.0.0 (including our mediation adapter libraries), that will make staying on Unity 5.4.0 more of a problem as time goes on.

**Comment by gagbaghdas** [comment]
Any updates on this? :(

**Comment by Vixxd** [comment]
+1

**Comment by qbit86** [comment]
@JillSong How are you progressing with this issue? Please let us know if there are any updates.

**Comment by ugurdeniz20** [comment]
Has anyone found any answer?

**Comment by sotirisFMG** [comment]
More Ping!!

**Comment by miragias** [comment]
Bump!

**Comment by qbit86** [comment]
@ericleich ?

**Comment by blueveno** [comment]
please update!

**Comment by KonstantKuz** [comment]
+1
Same problem using Applovin Max Sdk with Google AdMob adapter. Maybe someone knows how to revert Google Mobile Ads iOS SDK version in Max Sdk?

**Comment by rusitschka** [comment]
https://github.com/googleads/googleads-mobile-unity/compare/test_368723808 seems to support 8.0

**Comment by KrKgg** [comment]
Please update a final release version for Unity to be able to use it

**Comment by ComputerLunch** [comment]
What is the status of an updated on the Unity plugin? We are running into this issue for building for Iron Sources Admob unity adapter.

**Comment by KonstantKuz** [comment]
Found a solution. Maybe helps someone.

When I added the Applovin Max Sdk to the project and connected the Google Admob adapter, the GADU files were also added to the project in the Plugins-> iOS folder (there was an error in one of these GADU files), but I noticed that when I added the latest version of Applovin Max Sdk to the empty project and connected the Google Admob adapter - no files were added to the plugins folder.
Now I just removed the Plugins-> iOS folder from the project and it worked.

**Comment by JillSong** [comment]
Hey folks, we just dropped v6.0.0 that has support for GMA iOS SDK 8.0.0 and GAM  Android SDK 20.0.0. Please check it out! https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.0.0

**Comment by qbit86** [comment]
@JillSong What about updating mediation plugins?

**Comment by rivax95** [comment]
Same problem here, using the plugin updated to its latest version, any solution?

**Comment by SRubioMiranda** [comment]
Still failing in Admob Unity Plugin v6.0.1
Any solution?

**Comment by ericleich** [comment]
https://github.com/googleads/googleads-mobile-unity/commit/219bc85e7e82bbd04d89c5bfedd235bab43e2324#diff-93c0b8be17b2e63e7ccc8373accf117095fc186112ee2ed2fb54df57bec59b7f, released in 6.0.0 changed `GADURewardedAd` so that it:

- No longer references `GADRewardedAdDelegate`
- Doesn't call `initWithAdUnitID:` on `GADRewardedAd`

It should be impossible that you still have this issue on 6.x of the plugin. My guess is your project may still have an old copy of GADURewardedAd around. 6.x release I believe compiles the iOS code into a .a, so it may require removing the old .m files since the .a should have the library now, that sits in Assets/Plugins/Android.

@qbit86 we are working on updating the mediation plugins, ~7-8 of the more commonly used ones are live now with another 3-4 in the next couple of days. You can follow the network-specific guides, e.g. https://developers.google.com/admob/unity/mediation/facebook#facebook-unity-mediation-plugin-changelog, which link to the Android/iOS versions they include, and the release notes for the Android/iOS versions should confirm if the adapter is built against iOS v8.x or Android v20.x.

**Comment by chandujr** [comment]
> It should be impossible that you still have this issue on 6.x of the plugin. My guess is your project may still have an old copy of GADURewardedAd in your project.

By old copy do you mean a duplicate file? I have only one instance of GADURewardedAd.h and GADURewardedAd.m file in my Unity project. I'm also using v6.0.0.

**Comment by chandujr** [comment]
Okay this is how I fixed the issues with v6.0.0:

1. I had leftover files in _Plugins --> iOS_ folder from the previous version. Delete all the "_GADU...._" files in that folder.
2. Remove _GoogleMobileAds_ folder. If you are using mediation, just make sure to revert the dependencies.xml files in vcs after deleting this folder. It will usually be in _GoogleMobileAds --> Editor_ folder.
3. Import v6.0.0 plugin
4. Go to _Assets --> External Dependency Manager --> iOS Resolver --> Settings_ and enable the option "_Link frameworks statically_"
5. Create Xcode build. Inside the xcode project open the file "_GoogleMobileAds.iOS.cpp_" and comment out this line:

    `reinterpret_cast<PInvokeFunc>(GADURequestInterstitial)(___interstitial0, ___request1);`

    Source: https://github.com/googleads/googleads-mobile-unity/issues/1616#issuecomment-846713997

6. After doing all this, I'm able to make iOS build and ads are showing.

**Comment by newbision** [comment]
@chandujr I can't delete GoogleMobileAds folder, because I am using mediation(Adcolony, Applovin). I tried it with your steps. But it does not work.

**Comment by nntgam** [comment]
@chandujr your way not working for me. GADRewardedAdDelegate.

**Comment by chandujr** [comment]
> GADRewardedAdDelegate.

What about this?

**Comment by ozgurozel** [comment]
> Okay this is how I fixed the issues with v6.0.0:
> 
>     1. I had leftover files in _Plugins --> iOS_ folder from the previous version. Delete all the "_GADU...._" files in that folder.
> 
>     2. Remove _GoogleMobileAds_ folder.
> 
>     3. Import v6.0.0 plugin.
> 
>     4. If you are using mediation, make sure to revert the dependencies.xml files in _GoogleMobileAds_ folder using vcs now. They will usually be in _GoogleMobileAds --> Editor_ folder.
> 
>     5. Go to _Assets --> External Dependency Manager --> iOS Resolver --> Settings_ and enable the option "_Link frameworks statically_"
> 
>     6. Create Xcode build. Inside the xcode project open the file "_GoogleMobileAds.iOS.cpp_" and comment out this line:
>        `reinterpret_cast<PInvokeFunc>(GADURequestInterstitial)(___interstitial0, ___request1);`
>        Source: [Build iOS failed: Undefined symbols for architecture arm64: "_GADURequestInterstitial" #1616 (comment)](https://github.com/googleads/googleads-mobile-unity/issues/1616#issuecomment-846713997)
> 
>     7. After doing all this, I'm able to make iOS build and ads are showing.

This steps worked for me. i deleted ald GADU..... files under Plugins\ios folder and reinstall GoogleMobileAds package and tried to rebuild project and completeed the process.

**Comment by mani53-dev** [comment]
How to solve these errors with version 10.8.0?
