### ISSUE TITLE
Big bug last play services andorid sdk 10.0

### ISSUE THREAD

**Issue by ceceomer** [googleads/googleads-mobile-unity#312]
After update my android sdk from 9.80 to 10.0, my phone cant run apk.
Unity versiyon 5.4.3

**Comment by edumlauer** [comment]
Same here, it just asked me to update to 10.1 and still won't run.

**Comment by edumlauer** [comment]
Logcat output:
```
11-29 15:37:38.129 14561-14561/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.dupyx.filler, PID: 14561
                                                   java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/app/com.dupyx.filler-2/base.apk)
                                                       at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5084)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

I think it's also related to #314 and #313 . I was using Firebase (1.0.0), Play Game Services (0.9.35) and Admob (3.1.1) and it asked me to upgrade play services from 9.8 to 10.0, it crashed my app on laucnh. I don't remeber if it was at this moment that I upgraded Admob and Firebase to letates builds, but when I reopend Unity it asked me to update from 10.0 to 10.01 and still crashed. Removing all te Google Services files and reimporting didn't work either.

**Comment by rampara** [comment]
This issue is caused by Firebase and AdMob using conflicting Google Play services dependency versions. As a workaround, do the following:

1. Edit the versions of dependencies declared `Assets/Firebase/Editor/AppDeps.cs` from `"9.8+"` to `"LATEST"`. (Lines 43, 44, 45)
2. Delete the following files from the `Assets/Plugins/Android` directory of your Unity project
- `firebase-common-9.8.0`
- `firebase-common-9.8.0.meta`
- `firebase-iid-9.8.0`
- `firebase-iid-9.8.0.meta`
- `firebase-config-9.8.0`
- `firebase-config-9.8.0.meta`

There will updates made to the [Play Services Resolver library](https://github.com/googlesamples/unity-jar-resolver)  to account for conflicting version of dependencies, resolving this issue without the aforementioned workaround.

**Comment by edumlauer** [comment]
It's working perfectly now, thanks!

**Comment by chuakc92** [comment]
Yes, for anyone having these issues, look up ALL Deps files related to Google and change the "9.8+" to "LATEST". Remove any 9.8.0 files you may have in Android >> Plugins and Resolve Jars.

**Comment by rampara** [comment]
Closing this issue as the latest version of the Play Services Resolver library should account for conflicting versions of dependencies.
