### ISSUE TITLE
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/Interstitialad;

### ISSUE THREAD

**Issue by aceloq** [googleads/googleads-mobile-unity#1598]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.21f1
  * Google Mobile Ads Unity plugin version: 5.4.0
  * Platform: Android
  * Platform OS version: All
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions:  Facebook Audience Network 3.2.0

#### Steps to reproduce:

I last updated my app on 03/03/21. I was using the same version of Unity Editor, Google Mobile Ads and Facebook Audience Network Adapter. There is no problem and works fine. But now, I did External Dependency Manager/Android Resolver/Force Resolver without changing anything in the project , It doesn't work anymore.  Builds and the game runs smoothly. But it gives this error while creating the new interstitial ad.

"AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/Interstitialad;"

I later realized, Works fine with Play-Services-19.7.0 version But It doesn't work Play-Services-20.0.0 version and gives an error. Play Services Resolver automatically integrates Play-Services-20.0.0 version. I can't no longer roll back to Play-Services-19.7.0.

Google Mobile Ads Unity plugin needs to be updated urgently. It should compatible with Play-Services-20.0.0 version

**Comment by aceloq** [comment]
Edit : I deleted the Facebook Audience Network Adapter and I did Force Resolve. Play Services Resolver automatically integrates Play-Services-19.5.0 version and it works smoothly. I added Facebook Audience Network Adapter and I did Force Resolve again. This time, Play Services Resolver automatically integrated Play-Services-20.0.0 version and doesn't work anymore.

**Comment by perekstig** [comment]
I'm having the same problem. Is there no work-around at all?

**Comment by perekstig** [comment]
Today, after doing a resolve, suddenly it works successfully. I do not get the exception any longer. I just wish I know what's going on.

**Comment by ali-pjx** [comment]
> Today, after doing a resolve, suddenly it works successfully. I do not get the exception any longer. I just wish I know what's going on.

Are you by any chance using facebook mediation? (FB audience network)

because its still an open issue at [https://github.com/googleads/googleads-mobile-unity/issues/1591](url)
