### ISSUE TITLE
GoogleMobileAdsMediationTestSuite.unitypackage is too old

### ISSUE THREAD

**Issue by jasons-codes** [googleads/googleads-mobile-unity#1634]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.22f1
  * Google Mobile Ads Unity plugin version: 6.0.0
  * Platform: Android, UnityEditor
  * Platform OS version: Any
  * Any specific devices issue occurs on: Any
  * Mediation ad networks used, and their versions: audience-network-unity-sdk-6.2.1.unitypackage, GoogleMobileAdsMediationTestSuite.unitypackage

#### Steps to reproduce:

GoogleMobileAdsMediationTestSuite.unitypackage is too old and needs an upgrade to work with GoogleMobileAds-v6.0.0.unitypackage

#### Relevant Code:

```
Assets\GoogleMobileAdsMediationTestSuite\Platforms\Android\MediationTestClient.cs(146,53): error CS1061: 'AdRequest' does not contain a definition for 'TestDevices' and no accessible extension method 'TestDevices' accepting a first argument of type 'AdRequest' could be found (are you missing a using directive or an assembly reference?)
```

![image](https://user-images.githubusercontent.com/46530730/120442426-9112d600-c3c0-11eb-98fd-7a264983b0e2.png)

**Comment by Ommand** [comment]
And even if those lines are commented out, iOS still can not be built with a bunch of "Undefined symbols for architecture arm64" errors.

**Comment by ali-pjx** [comment]
@Ommand @jasons-codes 
If you are trying to fix this you can use requestConfiguration.TestDeviceIds(you can also add it in your google mobile ads script where you initialize google mobile ads and reference it here), however, even by fixing this issue, when I try to load ads in mediation test suite environment my app crashes. IDK what to do afterwards to fix this issue.

**Comment by ali-pjx** [comment]
@Ommand @jasons-codes 
I have also updated the mediation test suite dependency version in its xml file named "GoogleMobileAdsMediationTestSuiteDependencies" :

`<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.ads:mediation-test-suite:**2.0.0**">
      <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="GoogleMobileAdsMediationTestSuite" version="1.4.0">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
`
If you check the maven [repository()](https://mvnrepository.com/artifact/com.google.android.ads/mediation-test-suite/2.0.0) for this package you will find its upgraded version (v2.0.0) that had been released but admob haven't updated its dependency. Now if you do as above your mediation test suit will work.

**Comment by ali-pjx** [comment]
> And even if those lines are commented out, iOS still can not be built with a bunch of "Undefined symbols for architecture arm64" errors.

I have checked it out again on iOS it is still having this problem. However, on Android if you do as I said it is going to work.

**Comment by dawidahoy** [comment]
Same issue here. Version 2.0.0 solved problem for the Android. Unfortunately, iOS builds fail.

`Undefined symbols for architecture armv7:
  "_kGADAdLoaderAdTypeUnifiedNative", referenced from:
      -[GMTSNativeAdLoader initWithAdUnitId:rootViewController:] in GoogleMobileAdsMediationTestSuite(GMTSNativeAdLoader.o)
  "_OBJC_CLASS_$_DFPInterstitial", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_DFPRequest", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_DFPBannerView", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSProductTheme.o)
  "_OBJC_CLASS_$_GADRewardBasedVideoAd", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
  "_OBJC_CLASS_$_GADInterstitial", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAd)
  "_OBJC_CLASS_$_GADRequestError", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSMediationHelper.o)
  "_OBJC_CLASS_$_GADUnifiedNativeAd", referenced from:
      objc-class-ref in GoogleMobileAdsMediationTestSuite(GMTSAdSourceCollectionViewController.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by murilobast** [comment]
Any progress on this? This is a pretty important tool, shouldn't be incompatible with 6.0.0+

**Comment by ericleich** [comment]
Still working on updating the iOS build which will unblock creating a new .unitypackage. Timeline for this is a few weeks.

**Comment by mihailogazda** [comment]
+1 this is important tool and we need it fixed sooner rather than later. Is the code for this open? We can perhaps do so ourselves?

**Comment by zerosang** [comment]
You can use Ad inspector feature form Admob (https://support.google.com/admob/answer/10159602).
It work fine for me.

**Comment by Thaina** [comment]
> You can use Ad inspector feature form Admob (https://support.google.com/admob/answer/10159602).
> It work fine for me.

Are there a package for unity?

**Comment by raveneer** [comment]
In IOS, 

GoogleMobileAdsMediationTestSuiteDependencies.xml

changed 
 <iosPod name="GoogleMobileAdsMediationTestSuite" version="1.4.0">
to 
<iosPod name="GoogleMobileAdsMediationTestSuite" version="2.0.0">

build success.

**Comment by gayanW** [comment]
Any update on this? Suggested workarounds do not work in Unity.

**Comment by ali-pjx** [comment]
> > You can use Ad inspector feature form Admob (https://support.google.com/admob/answer/10159602).
> > It work fine for me.
> 
> Are there a package for unity?

No, you just follow the instructions on the support documents. But honestly, its not as handy as the Mediation test suite.

@gayanW nope, nothing that is officially accepted.

**Comment by gayanW** [comment]
@ali-pjx BTW do I need to import Audience Network Unity SDK in addition to Facebook Unity Adapter for the mediation to work?
The current 'Audience Network Unity SDK'  version is 6.4.0. But the adapter version is 3.3.0. I'm confused.

**Comment by Seanm07** [comment]
It's November and the unity version of the test suite still hasn't been updated for Google Mobile Ads v6 for android or iOS

@ericleich Any updates on when the unitypackage will be updated?
